config/routes.rb
SchoolWindow::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :universities

  root to: "pages#home"
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match "/help", to: "pages#help"
  match "/about", to: "pages#about"
  match "/contact", to: "pages#contact"

  match ':controller(/:action(/:id))(.:format)'
end

app/views/pages/about.html.erb
<% provide(:title, 'About us') %>
<div id="page"><h1>About Us</h1>
    <div id="content"><p><h2>Company Overview</h2></p>
    <p>We provide details of over 20,300 universities located in the world. We evaluate the standard
    of the universities from their current university world ranking and we provide all the universities'
    information for intending students. This ranking results are obtained
    from <a href="http://www.webometrics.info">Webometrics.info website</a>.</p></div>
    <div id="sidebar"><h3>Quick Links</h3>
            <ul class="links">
              <li><a href="/universities">University</a></li>
              <li><%= link_to 'Contact', contact_path %></li>
              <li><%= link_to 'Home', root_path %></li> 
            </ul>
    </div>
    <div itemscope="itemscope" itemtype="http://schema.org/LocalBusiness">
    <span itemprop="name">School-window</span>
    <div itemprop="address" itemscope="itemscope" itemtype="http://schema.org/PostalAddress">
        <span itemprop="streetAddress">25 Brierfield Terrace</span>
        <span itemprop="addressLocality">ABERDEEN</span>,
        <span itemprop="addressRegion">Scotland</span>
        <span itemprop="postalCode">AB16 5XT</span>
        <span itemprop="addressCountry">GB</span>
    </div>
    Phone: <span itemprop="telephone">+447748179270</span>
    Website: <a itemprop="URL">https://www.school-window.com</a>
</div>

</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div id="page">
<div id="content">
<h1>Contact Details</h1>  
  <p>Please click <a href="http://www.webometrics.info">here</a> to get
further details and contacts on universities. You can also reach us on:
  <li><strong>Phone number</strong> +447748179270</li>
  <li><strong>Email</strong> eseosaoshodin@yahoo.com</li></p>
  <%= image_tag("contact.jpg", :alt => "Education", :class=> "round")%></div>
  <div id="sidebar">
    <h3>Quick Links</h3>
            <ul class="links">
              <li><a href="/universities">University</a></li>
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'About us', about_path %></li>
            </ul>
  </div>
</div>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<div id="page"><h1> Help Centre</h1>
  <div id="content">
  <div id="accordion">
  <h3><a href="#">How to add a new University</a></h3>
  <div><ol>
  <li>Click on the "University" link</li>
  <li>You would be directed to sign-in or sign-up before viewing the University page</li>
  <li>From the University page, click on the "New University" link.</li>
  <li>Type in the name, Details and location of the university.</li>
  <li>Click on "Create University" button to add the university.</li>
  </ol></div>
  <h3><a href="#">How to change a University's detail</a></h3>
  <div><ol>
  <li>From the university page, click on the "edit" link.</li>
  <li>After making all the changes, click on the "Update" button to save the changes.</li>
  </ol></div>
  <h3><a href="#">How to search for an existing University</a></h3>
  <div><ol>
  <li>From the University page, Type in a keyword.</li>
  <li>Click on "Send" button to search for the University.</li>
  </ol></div>
  </div>
  </div>
  <div id="sidebar">
    <h3>Quick Links</h3>
            <ul class="links">
              <li><a href="/universities">University</a></li>
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'About us', about_path %></li>
            </ul>
  </div>
</div>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div id="page">
    <h2>University Window - Obtaining Knowledge Is Power</h2>
    <p>
      <div id="content">Are you looking for the best university close to you to attend? Then begin the road to success...
      search and add information of <a href="/universities">Universities</a> for the future. These Universities could be existing
      <a href="http://www.webometrics.info/">Universities</a> . <br/>
      <%= image_tag("search2.jpg", :alt => "Education", :class=> "round")%>
      </div>
      <div id="sidebar"><h3>Quick Links</h3>
            <ul class="links">
              <li><a href="/universities">University</a></li>
              <li><%= link_to 'Contact', contact_path %></li>
              <li><%= link_to 'About us', about_path %></li>
              <li><%= link_to 'Sign up', signup_path %></li>
              <li><a href="/signin">Login</a></li>
              <li><a href="http://www.webometrics.info/">News</a></li>
            </ul>
      </div>
    </p>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>