config/routes.rb
SchoolWindow::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :universities

  root to: "pages#home"
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match "/help", to: "pages#help"
  match "/about", to: "pages#about"
  match "/contact", to: "pages#contact"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/university.rb
# == Schema Information
#
# Table name: universities
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  location   :string(255)
#  details    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class University < ActiveRecord::Base
  attr_accessible :details, :location, :name
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_filter :signed_in_user
  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @universities }
    end
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
    @university = University.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @university }
    end
  end

  # GET /universities/new
  # GET /universities/new.json
  def new
    @university = University.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @university }
    end
  end

  # GET /universities/1/edit
  def edit
    @university = University.find(params[:id])
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(params[:university])

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render json: @university, status: :created, location: @university }
      else
        format.html { render action: "new" }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /universities/1
  # PUT /universities/1.json
  def update
    @university = University.find(params[:id])

    respond_to do |format|
      if @university.update_attributes(params[:university])
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university = University.find(params[:id])
    @university.destroy

    respond_to do |format|
      format.html { redirect_to universities_url }
      format.json { head :no_content }
    end
  end
  def search
    @universities = University.find(:all, :conditions => ["name LIKE ?", "%#{params[:key]}%"])
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in." 
    end
  end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/universities/_form.html.erb
<div class="row">
<div class="span6 offset3">
<%= form_for(@university) do |f| %>
  <% if @university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% @university.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-large btn-primary"%>
  </div>
<% end %>
</div>
</div>

app/views/universities/edit.html.erb
<h1>Editing university</h1>

<%= render 'form' %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<h1>Listing universities</h1>
<h2>Enter keyword</h3>
<div class="row">
<div class="span6 offset3">
<form action ="universities/search" method="post" >
<input name = "key" type="input" />
<input value="Send" type="submit" class="btn btn-large btn-primary"/>
</form>
</div>
</div>

<table border="1" class="centerT">
  <tr>
    <td width="15%"><p align="center"><i><b>Name</b></i></td>
    <td width="20%"><p align="center"><i><b>Location</b></i></td>
    <td width="40%"><p align="center"><i><b>Details</b></i></td>
  </tr>
  

<% @universities.each do |university| %>
  <tr>
    <td><%= university.name %></td>
    <td><%= university.location %></td>
    <td><%= university.details %></td>
    <td><%= link_to 'Show', university %></td>
    <td><%= link_to 'Edit', edit_university_path(university) %></td>
    <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New University', new_university_path %>

app/views/universities/new.html.erb
<h1>New university</h1>

<%= render 'form' %>

<%= link_to 'Back', universities_path %>

app/views/universities/search.html.erb
<html>
<head>
<title>Search results
</title>
</head>
<body>
<h1>Search results</h1>
<table border="1">
<tr>
<td width="40%"><p align="center"><i><b>University</b></i></td>
<td width="20%"><p align="center"><i><b>Location</b></i></td>
</tr>
<% @universities.each do |university| %>
<tr>
<td>
<a href="
<%=university.id%>
">
<%=university.name%>
</a>
</td>
<td><%= university.location %></td>
</tr>
<% end %>
</table>
<p> <a href="/universities"> Back</a> </body>
</html>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @university.name %>
</p>

<p>
  <b>Location:</b>
  <%= @university.location %>
</p>

<p>
  <b>Details:</b>
  <%= @university.details %>
</p>


<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>