config/routes.rb
SchoolWindow::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :universities

  root to: "pages#home"
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match "/help", to: "pages#help"
  match "/about", to: "pages#about"
  match "/contact", to: "pages#contact"

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="/universities">University</a>
    by Eseosa Oshodin
    <a href="http://www.refsnesdata.no/certification/w3certified.asp?id=4536637">
    <img src="assets/w3cert.png" border="0" /></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help",  help_path %></li>
      <li><a href="http://www.webometrics.info">Education News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <%= image_tag("logo.jpg", :alt => "Education", :class=> "round")%>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",  root_path %></li>
              <li><%= link_to "Help",  help_path %></li>
              <li><%= link_to "University", universities_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li id="fat-menu" class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                 </a>
                 <ul class="dropdown-menu">
                   <li><%= link_to "Profile", current_user %></li>
                   <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                   <li class="divider"></li>
                   <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                   </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            </ul>
          </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="description" content="This application website is a social networking application where different interested students or other users search and update details for  Universities.">
  <meta name="norton-safeweb-site-verification" content="241sp329h2vwrz3oca0yg-fikdn38iqovrwli8brei68utd1fvyilfhg3uu9ldj6w3gck11t7i-wfd-re26lrvbhn-a1u9jwisi6ikjw93usvygz3k8vh2eke4h830di" />
  <META NAME="ROBOTS" CONTENT="INDEX, FOLLOW, ARCHIVE" />
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37642329-1']);
  _gaq.push(['_setDomainName', 'school-window.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/jquery-ui.min.js"></script>
    <script>
      $(function(){$( "#accordion" ).accordion();});
    </script>
  <style type="text/css" media="screen">
      #content {
        float: none;
        background-color: #d3d3d3;
        border: 3px solid #aaa;
        margin-left: 100px;
        border-top: none;
        padding: 25px;
        width: 600px;
      }
      #sidebar {
        float: none;
        width: 175px;
        margin-left: 690px;
      }
      #sidebar ul {
        margin-left: 0;
        padding-left: 0;
      }
      #sidebar ul h3 {
        margin-top: 25px;
        font-size: 16px;
        padding-bottom: 10px;
        border-bottom: 1px solid #ccc;
      }
      #sidebar li {
        list-style-type: none;
      }
      
      #sidebar ul.links li {
        margin-bottom: 5px;
        
      }
      
      #page {
        background-color: #a9a9a9;
        width: 800px;
        margin: 0;
        margin-left: auto;
        margin-right: auto;
        padding: 20px;
      }
  </style>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>